config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/shop', to: 'pages#shop'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
#see https://stripe.com/docs/checkout/rails
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

	def shop
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class='navbar navbar-default'>
  <div class='container'>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Shop', shop_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><Andelins Candies></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 	<body>
    <link href='https://fonts.googleapis.com/css?family=Limelight|Open+Sans' rel='stylesheet'> 
		<%= render 'layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class='plate jumbotron'>
	<h1>Our story...</h1>
	
</div>

app/views/pages/contact.html.erb
<div class='plate jumbotron'>
	<h1>Contact info</h1>
	
</div>

app/views/pages/home.html.erb
<div class='plate jumbotron'>
	<h1 class='brand'>Andelin's</h1>
	<h2 class='limelight'>Caramel Pecan Rolls and other Decadent Sweets</h2>
	<%= image_tag("key2.jpg", :alt => "key", class: "key img-responsive image") %>
		<div class='contact'>
			<h2>For orders or inquiries, please contact us at:</h2>
		</div>
		<div class='contact'>
			<h2>andelinscandy@gmail.com</h2>
		</div>
</div>

app/views/pages/shop.html.erb
<div class='plate jumbotron'>
	<h1>Shopping page</h1>
	
</div>